---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root

  tasks: 
    - name: Update apt cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    
    - name: Reboot
      reboot:
    
