- hosts: all
  vars:
    ansible_user: USER_NAME
    ansible_password: USER_PASSWORD
    ansible_port: 5986
    ansible_connection: winrm

  tasks:
    - name: Basic ping 
      win_ping:

    - name: Create file with some text
      win_dsc:
        resource_name: File
        DestinationPath: C:\temp\HelloWorld.txt
        Contents: |
          Hello
          World
        Ensure: Present
        Type: File
