---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root

  tasks:
    - name: Enable cgroups (update /boot/firmware/cmdline.txt)
      template:
        src: templates/boot_firmware_cmdline.txt.template
        dest: /boot/firmware/cmdline.txt
        owner: root
        group: root
        mode: '0755'

    - name: Reboot
      reboot:
    

