---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Enable cgroups 1 (add /etc/docker/daemon.json)
      template:
        src: ./templates/etc_docker_daemon.json.template
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'

    - name: Enable cgroups 2 (update /boot/firmware/cmdline.txt)
      template:
        src: templates/boot_firmware_cmdline.txt.template
        dest: /boot/firmware/cmdline.txt
        owner: root
        group: root
        mode: '0755'

    - name: Allow iptables to see bridged traffic
      template:
        src: templates/etc_sysctl.d_k8s.conf.template
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable docker service
      systemd:
        name: docker.service
        enabled: yes
        state: started
          
    # - name: Reboot
    #   reboot:
    

