
---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root

  tasks:
    - name: Install microk8s
      snap:
        name: microk8s
        classic: yes

    - name: Join the cluster
      shell: microk8s.join {{ connection_string }}
      async: 1
      poll: 0
