---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root

  tasks: 
    - name: Update the host name
      hostname:
        name: "{{ network_name }}"

    - name: Disable Cloud Init
      template:
        src: ./99-disable-config.cfg.template
        dest: /etc/cloud/cloud.cfg.d/99-disable-config.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Copy new network configuration
      template:
        src: ./01-netcfg.yaml.template
        dest: /etc/netplan/01-netcfg.yaml
        owner: root
        group: root
        mode: '0644'
    
    - name: Update new network configuration ip address
      replace:
        path: /etc/netplan/01-netcfg.yaml
        regexp: 'REPLACE_ME'
        replace: "{{ network_ip }}"

    - name: Remove cloud-init yaml file
      file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent 

    - name: Reboot (via shutdown to avoid waiting for coming back up)
      shell: /usr/bin/sleep 5 && /usr/sbin/shutdown -r now
      async: 1
      poll: 0
      become: true
      ignore_errors: true
